name: Joga Moterims Su Vilma
favicon: null
layout_spectrum: 0.56798
typography_spectrum: 0.46309
title: Joga Moterims Su Vilma
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73791543-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbb6b9'
    - '#fefeda'
    - '#fe5c74'
    - '#d01f00'
    - '#9b6c00'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
