name: Joga Moterims Su Vilma
favicon: null
layout_spectrum: 0.22779
typography_spectrum: 0.44338
title: Joga Moterims Su Vilma
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73791543-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000800'
    - '#fefaf1'
    - '#ffcb57'
    - '#720000'
    - '#fe4900'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
