name: Joga Moterims
favicon: null
layout_spectrum: 0.07676521735265851
typography_spectrum: 0.642795970896259
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7550143508706242
  lightness: 0.383443770930171
  saturation: 0.7751129462849349
  rhythmicContrast: 0.5221422084141523
purpose: []
