name: Joga Moterims Su Vilma
favicon: null
layout_spectrum: 0.22779
typography_spectrum: 0.44338
title: Joga Moterims Su Vilma
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73791543-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff1d0'
    - '#ff0074'
    - '#ffa57e'
    - '#00d5c7'
    - '#3400a6'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
