name: JogaMoterimSuVilma
favicon: null
layout_spectrum: 1
typography_spectrum: 0.642795970896259
title: JogaMoterims
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: "<script>   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){   (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)   })(window,document,'script','//www.google-analytics.com/analytics.js','ga');    ga('create', 'UA-73682648-1', 'auto');   ga('send', 'pageview');  </script>"
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#da0000'
    - '#f15d00'
    - '#823400'
    - '#f1e44b'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0
purpose: []
