typography_spectrum: 0.48764
color:
  brandColors:
    - '#fefddf'
    - '#5a806b'
    - '#fd2300'
    - '#f3b062'
    - '#7b0801'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.56798
analytics:
  google: UA-73791543-1
  facebook: null
  twitter: null
author:
  name: i_vil
  url: 'http://jogamoterimssuvilma.lt/'
  email: vilmaw2000@yahoo.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e4125035-4d7e-46e4-b43d-a2a100a45d54.jpg
name: Joga Moterims Su Vilma
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: VILMA
    id: b5ca9b1e-7b4b-40b9-86fd-6b89d4c9637d
    type: content
  - name: DUK
    id: 855ac7ff-d9d4-4ba4-b188-b3aa94b00a69
    type: content
  - name: 2016 TURAS LIETUVOJE
    id: d53a67a2-f1d0-41ad-ad77-954c9c67724d
    type: content
  - name: 'KAINA '
    id: 56eb2114-8096-4daf-81f5-5b0fd6af4f33
    type: content
  - name: KONTAKTAI
    id: 53bfaa71-2058-4a18-9b07-b70c6904b188
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/39f618d4-d307-42ad-a357-bea3869e9baa.jpg
title: Joga Moterims Su Vilma
description: '"Joga KITAIP - nuostabus patyrimas!" - Dalia'
purpose: []
