name: Joga Moterims Su Vilma
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44573
title: Joga Moterims Su Vilma
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c96d21'
    - '#694218'
    - '#c73900'
  brandStrength: 0
  lightness: 0
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
