name: Joga Moterims Su Vilma
favicon: null
layout_spectrum: 0.56798
typography_spectrum: 0.25334
title: Joga Moterims Su Vilma
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73791543-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#aede00'
    - '#a469bd'
    - '#006b00'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
