name: Joga Moterims Su Vilma
favicon: null
layout_spectrum: 0.56798
typography_spectrum: 0.86098
title: Joga Moterims Su Vilma
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73791543-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefad5'
    - '#f7bd74'
    - '#520000'
    - '#d05100'
    - '#697983'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
