name: Joga Moterims Su Vilma
favicon: null
layout_spectrum: 0.56798
typography_spectrum: 0.46309
title: Joga Moterims Su Vilma
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73791543-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefddf'
    - '#5a806b'
    - '#fd2300'
    - '#f3b062'
    - '#7b0801'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
