name: Joga Moterims Su Vilma
favicon: null
layout_spectrum: 0.61812
typography_spectrum: 0.25334
title: Joga Moterims Su Vilma
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73791543-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4e82a9'
    - '#ffffff'
    - '#ff9062'
    - '#fdd193'
    - '#7d6a5c'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 1
purpose: []
