name: Joga Moterims Su Vilma
favicon: null
layout_spectrum: 0.56798
typography_spectrum: 0.49066
title: Joga Moterims Su Vilma
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73791543-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffda8a'
    - '#103756'
    - '#7b6e5e'
    - '#fffc01'
    - '#51a337'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
