typography_spectrum: 0.48764
color:
  brandColors:
    - '#fefddf'
    - '#5a806b'
    - '#fd2300'
    - '#f3b062'
    - '#7b0801'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.56798
analytics:
  google: UA-73791543-1
  facebook: null
  twitter: null
author:
  name: i_vil
  url: 'http://jogamoterimssuvilma.lt/'
  email: vilmaw2000@yahoo.com
logo: null
name: Joga Moterims Su Vilma
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/39f618d4-d307-42ad-a357-bea3869e9baa.jpg
title: Joga Moterims Su Vilma
description: '"Joga KITAIP - nuostabus patyrimas!" - Dalia'
purpose: []
