name: Joga Moterims Su Vilma
favicon: null
layout_spectrum: 0.22779
typography_spectrum: 0.44338
title: Joga Moterims Su Vilma
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73791543-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dc0000'
    - '#ffffff'
    - '#f46200'
    - '#844000'
    - '#bab100'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
